console.log("=== TEST GYRO v2 (con pausa antes del reset) ===")
motors.largeBC.stop()
pause(500)
sensors.gyro4.reset()
pause(500)
console.log("Ángulo tras reset y pausa: [" + sensors.gyro4.angle() + "]")

motors.largeBC.tank(20, -20)
pause(1000)
console.log("Ángulo después de girar 1 segundo: [" + sensors.gyro4.angle() + "]")
motors.largeBC.stop()
